### ISSUE TITLE
Some issues in compiling TBB for Intel, from CRAN

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.textmodels#65]
See [Intel](https://www.stats.ox.ac.uk/pub/bdr/Intel/quanteda.textmodels.out) Issues at https://cran.r-project.org/web/checks/check_results_quanteda.textmodels.html. 

@koheiw any chance you could fix this, before CRAN puts us in the naughty corner?

**Comment by koheiw** [comment]
The problem is coming from the extensive use of **RcppParallel** in `textmodel_wordfish()`. I don't know who wrote the code and if it is worth rewriting it using newer TBB.

https://github.com/quanteda/quanteda.textmodels/blob/master/src/wordfish_mt.cpp

Why don't you delete the C++ code for `sparse = TRUE`.
