### ISSUE TITLE
better doc of smooth parameter of textmodel_nb

### ISSUE THREAD

**Issue by jwijffels** [quanteda/quanteda.textmodels#9]
It would be nice if the documentation of the smooth argument in textmodel_nb was a bit more explicit on what it does.
If I look to 
https://github.com/quanteda/quanteda/blob/583fb284687d5bf7283b7bf71dff6693ee04966e/R/textmodel_nb.R#L141
https://github.com/quanteda/quanteda/blob/583fb284687d5bf7283b7bf71dff6693ee04966e/R/textmodel_nb.R#L144
It basically adds the 'smooth' term to the document term matrix before weighting. In my use cases, optimising this parameter has a dramatic impact on performance. It's always nice to understand what it does. The docs at https://github.com/quanteda/quanteda/blob/583fb284687d5bf7283b7bf71dff6693ee04966e/R/textmodel_nb.R#L10 now indicate: `smooth smoothing parameter for feature counts by class`, why not just `smooth number added to each cell in the dfm to smooth out and give more weight to infrequent term occurrences`

**Comment by kbenoit** [comment]
Thanks @jwijffels for the suggestion. To be precise, it's not adding the smoothing amount to each cell in the dfm, but only to each feature in the _grouped_ dfm, after collecting all feature counts by training class. The class-grouped dfm tends to be a lot less sparse than the dfm with the original documents, but the performance hit still happens because the smoothed dfm will be dense (even though technically, it remains a "sparseMatrix" class).

How could I explain that in the documentation more clearly? Suggestions welcome!

Your note about performance led me to do some tests, which I put into the branch `nb-performance-trial`. I tried manipulating the non-sparse elements of the dfm directly when smoothing but the problem is at some point, the zeros still need the smoothing amount added. There's no way around this if we want to keep the sparse matrix multiplication methods required to perform the computations to get class posteriors.

In my tests, there was no performance gain to justify using the ugly hack I wrote. 
``` r
library("quanteda.textmodels")
## Loading required package: quanteda
## Package version: 2.0.0

data(data_corpus_LMRD, package = "quanteda.classifiers")
dfmat <- dfm(data_corpus_LMRD)

# uses new quanteda v2 syntax for docvar access
microbenchmark::microbenchmark(
  tmod_nb = textmodel_nb(dfmat, y = dfmat$polarity, smooth = 1),
  tmod_nb2 = textmodel_nb2(dfmat, y = dfmat$polarity, smooth = 1),
  times = 10
)
## Unit: milliseconds
##      expr       min       lq     mean   median       uq      max neval
##   tmod_nb 1040.6782 1067.422 1090.169 1074.677 1111.257 1162.135    10
##  tmod_nb2  904.4543 1046.107 1057.002 1069.897 1099.057 1123.329    10
```

Feel free (anyone!) to see if they can improve the efficiency. Otherwise these results are not enough to justify replacing parsimonious code with an ugly hack:
https://github.com/quanteda/quanteda.textmodels/blob/def100ef828372559b4fdb1e8d7b5577d6c676fd/R/textmodel_nb2.R#L140-L154

**Comment by jwijffels** [comment]
Why not: smooth number added to the feature frequencies to smooth out and give more weight to infrequent term occurrences. This smooth term is added for the non-zero occcurrences of terms within each target label.

Regarding performance I meant classification accuracy. Apologies if this was not clear and this led you into an unnecessary investigation

**Comment by kbenoit** [comment]
Ah ok, thanks for clarifying! Performance is important. It still needs improvement, and possible a slight model change, for the Bernoulli implementation (see #3) but it's on the short list.

I will update the documentation as you suggest.
